"""Demo knowledge card seed definitions."""

SEED_KNOWLEDGE_CARDS = [
    {
        "title": "登录失败提示账号无权限处理办法",
        "question": "客户登录失败并提示账号无权限时如何排查？",
        "answer": "先确认账号是否已开通、是否分配正确角色，并核对登录环境/租户是否正确。",
        "system_name": "业务系统",
        "module_name": "登录权限",
        "tags": "登录,权限,账号无权限",
        "scene": "客户现场登录系统失败",
        "reason_analysis": "常见原因包括账号未开通、角色未分配、环境/租户选择错误或权限缓存未刷新。",
        "troubleshooting_steps": "1. 核对账号状态是否启用\n2. 检查角色与菜单权限是否分配\n3. 确认登录地址与环境是否匹配\n4. 查看登录日志定位拒绝原因",
        "solution": "补全账号权限后重新登录；必要时重置密码并同步账号信息。",
        "risk_notice": "生产环境调整权限前需人工确认，避免误开放高权限。",
        "source_group": "实施群",
        "source_user": "admin",
        "audit_status": "approved",
        "audit_remark": "演示数据",
    },
    {
        "title": "接口返回404或资源不存在处理办法",
        "question": "系统接口返回404或提示资源不存在时如何处理？",
        "answer": "先核对接口地址、请求方法、路径参数和网关路由配置是否正确。",
        "system_name": "业务系统",
        "module_name": "接口调用",
        "tags": "接口,404,资源不存在",
        "scene": "前后端联调或现场调用接口报错",
        "reason_analysis": "常见原因包括 URL 拼写错误、接口版本变更、网关路由未发布或资源 ID 不存在。",
        "troubleshooting_steps": "1. 核对接口文档与真实请求 URL\n2. 检查请求方法与 Content-Type\n3. 确认网关/反向代理路由\n4. 在测试环境复现并查看服务日志",
        "solution": "修正接口路径或发布缺失路由；如资源不存在需确认业务数据是否已创建。",
        "risk_notice": "生产环境修改网关路由前请先在测试环境验证。",
        "source_group": "实施群",
        "source_user": "admin",
        "audit_status": "approved",
        "audit_remark": "演示数据",
    },
    {
        "title": "客户现场无法连接数据库处理办法",
        "question": "客户现场应用无法连接数据库时如何排查？",
        "answer": "按网络连通性、数据库服务状态、连接串配置、账号权限顺序逐步排查。",
        "system_name": "业务系统",
        "module_name": "数据库连接",
        "tags": "数据库,连接失败,网络",
        "scene": "现场部署后应用启动或访问时报数据库连接失败",
        "reason_analysis": "常见原因包括防火墙拦截、数据库服务未启动、连接地址/端口错误、账号权限不足。",
        "troubleshooting_steps": "1. ping/telnet 检查网络与端口\n2. 确认数据库服务运行状态\n3. 核对连接串、实例名、字符集\n4. 用客户端工具测试同一账号连接",
        "solution": "放通网络策略并修正连接配置；必要时由 DBA 重置账号或授权。",
        "risk_notice": "不要在日志或群里传播明文数据库密码。",
        "source_group": "实施群",
        "source_user": "admin",
        "audit_status": "approved",
        "audit_remark": "演示数据",
    },
    {
        "title": "系统菜单看不到或按钮权限缺失处理办法",
        "question": "用户登录后看不到系统菜单或按钮权限缺失怎么办？",
        "answer": "检查用户角色、菜单授权、按钮权限配置以及权限缓存是否生效。",
        "system_name": "业务系统",
        "module_name": "菜单权限",
        "tags": "菜单,按钮,权限",
        "scene": "用户反馈看不到菜单或关键按钮灰色不可用",
        "reason_analysis": "常见原因包括角色未绑定菜单、按钮权限未授权、组织范围限制或缓存未刷新。",
        "troubleshooting_steps": "1. 查看用户绑定角色\n2. 检查角色菜单/按钮授权\n3. 确认数据权限范围\n4. 清理权限缓存并重新登录",
        "solution": "补齐角色授权后让用户重新登录；必要时同步组织权限。",
        "risk_notice": "批量授权前请确认影响范围，避免扩大权限。",
        "source_group": "实施群",
        "source_user": "admin",
        "audit_status": "approved",
        "audit_remark": "演示数据",
    },
    {
        "title": "文件上传失败或附件无法预览处理办法",
        "question": "文件上传失败或附件无法预览时如何处理？",
        "answer": "检查文件大小/格式限制、存储目录权限、预览组件配置及网络代理限制。",
        "system_name": "业务系统",
        "module_name": "附件管理",
        "tags": "上传,附件,预览",
        "scene": "用户上传附件失败或上传后无法在线预览",
        "reason_analysis": "常见原因包括超过大小限制、格式不在白名单、存储路径无写权限或预览服务异常。",
        "troubleshooting_steps": "1. 核对上传大小与格式限制\n2. 检查存储目录权限与磁盘空间\n3. 查看应用日志中的上传异常\n4. 验证预览服务依赖是否可用",
        "solution": "调整配置或修复存储权限；必要时手工迁移附件并重启相关服务。",
        "risk_notice": "修改存储路径或权限前请备份现有附件数据。",
        "source_group": "实施群",
        "source_user": "admin",
        "audit_status": "approved",
        "audit_remark": "演示数据",
    },
]
